/**
 * scripts/audits/06_hygiene_ai_clean.audit.js
 * Dominio 6: Higiene de Código y Detección de Vestigios de IA (Clean Code & No-AI Footprint)
 * 
 * Evalúa que el código de producción no contenga:
 *  - Menciones explícitas a modelos, asistentes o herramientas de IA (ChatGPT, Copilot, Claude, Gemini, etc.).
 *  - Comentarios típicos de generación de LLM (ej. "rest of code unchanged", "as requested by user").
 *  - Residuos de edición o bloques de diff ([diff_block_start], conflictos de merge).
 *  - Comentarios sobre-explicativos artificiales que narran pasos de prompts.
 */

const fs = require('fs');
const path = require('path');

module.exports = {
  id: 'hygiene',
  name: 'Higiene de Código y Vestigios de IA',

  run(ctx, addIssue) {
    const filesToAudit = [];

    // Todos los archivos JS de public/
    const publicJs = ctx.getJsFiles();
    filesToAudit.push(...publicJs);

    // Archivos en src/
    const collectFromDir = (dir) => {
      if (!fs.existsSync(dir)) return;
      const entries = fs.readdirSync(dir, { withFileTypes: true });
      for (const entry of entries) {
        const full = path.join(dir, entry.name);
        if (entry.isDirectory()) {
          collectFromDir(full);
        } else if (entry.isFile() && (entry.name.endsWith('.js') || entry.name.endsWith('.html'))) {
          filesToAudit.push(full);
        }
      }
    };
    collectFromDir(ctx.srcDir);

    // Archivos raíz de producción
    const rootFiles = ['main.js', 'preload.js', 'public/index.html']
      .map(f => path.join(ctx.rootDir, f))
      .filter(f => fs.existsSync(f));
    filesToAudit.push(...rootFiles);

    // 2. Definición de patrones de vestigios de IA
    const PATTERNS = [
      {
        id: 'AI_EXPLICIT_MENTION',
        regex: /\b(chatgpt|openai|copilot|github copilot|anthropic|claude|gemini ai|deepseek|deepmind|antigravity|cursor ai|v0\.dev|tabnine|codeium)\b/i,
        message: 'Mención explícita a plataforma o modelo de IA detectada en el código/comentarios.',
        suggestion: 'Elimine cualquier referencia a herramientas de IA para preservar la autoría institucional limpia.'
      },
      {
        id: 'AI_PROMPT_JARGON',
        regex: /\b(as an ai|as requested by user|per user prompt|per user request|generated by ai|ai assistant|ai-generated|written by ai|prompt requirement)\b/i,
        message: 'Jerga característica de instrucciones o prompts de IA encontrada.',
        suggestion: 'Remueva comentarios que hagan alusión a prompts o solicitudes de usuario como origen del código.'
      },
      {
        id: 'AI_OMISSION_MARKER',
        regex: /(\/\/\s*|\/\*+\s*|\<!--\s*)(\.\.\.rest of code|\.\.\.existing code|rest of code unchanged|existing code remains|rest remains unchanged|code continues as before|insert implementation here|replace with your actual)/i,
        message: 'Residuo de omisión o placeholder de código típico de generación de IA detectado.',
        suggestion: 'Verifique que no haya código recortado u omitido y remueva comentarios de relleno.'
      },
      {
        id: 'AI_DIFF_MARKER',
        // Marcadores estrictos de conflicto Git (exactamente 7 caracteres al inicio) o marcas diff
        regex: /^<{7}\s.*$|^={7}$|^>{7}\s.*$|\[diff_block_start\]|\[diff_block_end\]/,
        message: 'Marcador residual de herramientas de parche o conflicto Git detectado en el archivo.',
        suggestion: 'Elimine el marcador residual antes de enviar el archivo a producción.'
      },
      {
        id: 'AI_STEP_META_COMMENT',
        regex: /\/\/\s*(step \d+:\s*(now we|let's|we will|here we)|in this step we|this function was modified to fulfill)/i,
        message: 'Meta-comentario narrativo sobre-explicativo de IA detectado.',
        suggestion: 'Elimine los comentarios que narran pasos de razonamiento o tareas de prompting.'
      },
      {
        id: 'FORBIDDEN_INSTITUTIONAL_VOCABULARY',
        regex: /(?:>|["'`])\s*[^<"'`]*\b(formato|versión|version|datos|registro|información|informacion|fuente|canal|plataforma|reporte)\s+oficial(?:es)?\b/i,
        message: 'Uso del término redundante/prohibido "oficial" en texto visible de la interfaz. Directriz de negocio: Todo es oficial.',
        suggestion: 'Elimine la palabra "oficial" del texto de interfaz o plantilla visible.'
      }
    ];

    // 3. Inspección línea a línea
    for (const filePath of filesToAudit) {
      const lines = ctx.getFileLines(filePath);

      for (let i = 0; i < lines.length; i++) {
        const lineContent = lines[i];
        const trimmed = lineContent.trim();
        const lineNum = i + 1;

        for (const pattern of PATTERNS) {
          const match = trimmed.match(pattern.regex);
          if (match) {
            addIssue(
              'code_hygiene',
              filePath,
              lineNum,
              `[${pattern.id}] ${pattern.message} Coincidencia: "${match[0]}"`,
              pattern.suggestion,
              trimmed,
              'error'
            );
            break;
          }
        }
      }
    }
  }
};
